create table if not exists public.product_images (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  image_url text not null,
  position integer not null default 0 check (position >= 0),
  created_at timestamptz not null default now()
);

create index if not exists product_images_product_id_position_idx
  on public.product_images (product_id, position);

alter table public.product_images enable row level security;

grant select, insert, update, delete on table public.product_images to authenticated;

drop policy if exists "Administradores gerenciam imagens de produtos" on public.product_images;
create policy "Administradores gerenciam imagens de produtos"
  on public.product_images
  for all
  to authenticated
  using ((select public.is_admin()))
  with check ((select public.is_admin()));
