-- Registro de conferências de produtos por QR Code durante a logística.
-- Um QR identifica o tipo de produto; a quantidade conferida é a quantidade da reserva.

create table if not exists public.reservation_item_qr_scans (
  id bigint generated by default as identity primary key,
  reservation_id bigint not null references public.reservations(id) on delete cascade,
  reservation_item_id bigint not null references public.reservation_items(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete restrict,
  stage text not null check (stage in ('preparing', 'delivered', 'returned')),
  checked_quantity integer not null check (checked_quantity > 0),
  checked_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (reservation_item_id, stage)
);

create index if not exists reservation_item_qr_scans_reservation_stage_idx
  on public.reservation_item_qr_scans (reservation_id, stage);

alter table public.reservation_item_qr_scans enable row level security;

grant select, insert, update, delete on public.reservation_item_qr_scans to authenticated;
grant usage, select on sequence public.reservation_item_qr_scans_id_seq to authenticated;
revoke all on public.reservation_item_qr_scans from anon;

create policy "Administradores gerenciam conferencias por QR"
  on public.reservation_item_qr_scans
  for all
  to authenticated
  using ((select public.is_admin()))
  with check ((select public.is_admin()));
