create table if not exists public.reservation_payments (
  id bigint generated by default as identity primary key,
  reservation_id bigint not null references public.reservations(id) on delete cascade,
  amount numeric(12, 2) not null check (amount > 0),
  payment_date date not null default current_date,
  payment_method text not null default 'other' check (payment_method in ('pix', 'cash', 'card', 'transfer', 'other')),
  notes text,
  created_at timestamptz not null default now()
);

create index if not exists reservation_payments_reservation_id_idx
  on public.reservation_payments(reservation_id);

create index if not exists reservation_payments_payment_date_idx
  on public.reservation_payments(payment_date desc);

grant select, insert, update, delete on table public.reservation_payments to authenticated;
grant usage, select on sequence public.reservation_payments_id_seq to authenticated;

alter table public.reservation_payments enable row level security;

create policy "Administradores gerenciam pagamentos de reservas"
  on public.reservation_payments
  for all
  to authenticated
  using ((select public.is_admin()))
  with check ((select public.is_admin()));

create or replace function public.sync_reservation_amount_paid()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  target_reservation_id bigint;
begin
  target_reservation_id := coalesce(new.reservation_id, old.reservation_id);

  update public.reservations
  set amount_paid = coalesce((
    select sum(amount)
    from public.reservation_payments
    where reservation_id = target_reservation_id
  ), 0)
  where id = target_reservation_id;

  return coalesce(new, old);
end;
$$;

revoke execute on function public.sync_reservation_amount_paid() from public, anon, authenticated;

drop trigger if exists sync_reservation_amount_paid_after_payment on public.reservation_payments;

create trigger sync_reservation_amount_paid_after_payment
after insert or update or delete on public.reservation_payments
for each row execute function public.sync_reservation_amount_paid();

insert into public.reservation_payments (reservation_id, amount, payment_date, payment_method, notes)
select
  id,
  amount_paid,
  current_date,
  'other',
  'Pagamento registrado antes do histórico de pagamentos.'
from public.reservations
where amount_paid > 0
  and not exists (
    select 1
    from public.reservation_payments
    where reservation_payments.reservation_id = reservations.id
  );
