-- Controle de estoque mínimo e conferência de devolução das locações.

alter table public.products
  add column if not exists minimum_stock integer not null default 5;

alter table public.products
  drop constraint if exists products_minimum_stock_check;

alter table public.products
  add constraint products_minimum_stock_check
  check (minimum_stock >= 0);

create index if not exists products_active_stock_quantity_idx
  on public.products (active, stock_quantity);

create table if not exists public.reservation_return_items (
  id bigint generated by default as identity primary key,
  reservation_id bigint not null references public.reservations(id) on delete cascade,
  reservation_item_id bigint not null references public.reservation_items(id) on delete cascade,
  product_id bigint references public.products(id) on delete restrict,
  expected_quantity integer not null check (expected_quantity > 0),
  returned_quantity integer not null default 0 check (returned_quantity >= 0),
  damaged_quantity integer not null default 0 check (damaged_quantity >= 0),
  lost_quantity integer not null default 0 check (lost_quantity >= 0),
  notes text,
  checked_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (reservation_item_id),
  check (returned_quantity + damaged_quantity + lost_quantity <= expected_quantity)
);

create index if not exists reservation_return_items_reservation_id_idx
  on public.reservation_return_items (reservation_id);

alter table public.reservation_return_items enable row level security;

grant select, insert, update, delete on public.reservation_return_items to authenticated;
grant usage, select on sequence public.reservation_return_items_id_seq to authenticated;
revoke all on public.reservation_return_items from anon;

drop policy if exists "Administradores gerenciam devoluções" on public.reservation_return_items;
create policy "Administradores gerenciam devoluções"
  on public.reservation_return_items
  for all
  to authenticated
  using ((select public.is_admin()))
  with check ((select public.is_admin()));

create or replace function public.update_reservation_return_items_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

revoke all on function public.update_reservation_return_items_updated_at() from public;

drop trigger if exists reservation_return_items_updated_at on public.reservation_return_items;
create trigger reservation_return_items_updated_at
before update on public.reservation_return_items
for each row execute function public.update_reservation_return_items_updated_at();
