create table if not exists public.reservation_logistics_checklist (
  id bigint generated by default as identity primary key,
  reservation_id bigint not null references public.reservations(id) on delete cascade,
  item_key text not null check (
    item_key in (
      'items_checked',
      'vehicle_loaded',
      'assembly_completed',
      'return_checked'
    )
  ),
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  unique (reservation_id, item_key)
);

create index if not exists reservation_logistics_checklist_reservation_id_idx
  on public.reservation_logistics_checklist (reservation_id);

grant select, insert, update, delete
  on table public.reservation_logistics_checklist to authenticated;

alter table public.reservation_logistics_checklist enable row level security;

create policy "Administradores gerenciam checklist de logistica"
  on public.reservation_logistics_checklist
  for all
  to authenticated
  using ((select public.is_admin()))
  with check ((select public.is_admin()));
