-- Produtos podem ter uma situação operacional sem desaparecer do catálogo.
-- Somente produtos "disponivel" devem entrar em novas locações.
alter table public.products
  add column if not exists maintenance_status text not null default 'disponivel',
  add column if not exists maintenance_notes text,
  add column if not exists is_kit boolean not null default false;

alter table public.products
  drop constraint if exists products_maintenance_status_check;

alter table public.products
  add constraint products_maintenance_status_check
  check (maintenance_status in ('disponivel', 'limpeza', 'manutencao', 'avariado'));

comment on column public.products.maintenance_status is
  'Situacao operacional: disponivel, limpeza, manutencao ou avariado.';
comment on column public.products.maintenance_notes is
  'Observacoes internas sobre limpeza, manutencao ou avarias.';
comment on column public.products.is_kit is
  'Indica que o produto e uma composicao formada por outros produtos.';

create table if not exists public.product_kit_items (
  id bigint generated by default as identity primary key,
  kit_product_id bigint not null references public.products(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete restrict,
  quantity integer not null check (quantity > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (kit_product_id, product_id),
  check (kit_product_id <> product_id)
);

comment on table public.product_kit_items is
  'Itens que compoem um produto marcado como kit.';

create index if not exists product_kit_items_kit_product_id_idx
  on public.product_kit_items (kit_product_id);
create index if not exists product_kit_items_product_id_idx
  on public.product_kit_items (product_id);
create index if not exists products_maintenance_status_idx
  on public.products (maintenance_status);

alter table public.product_kit_items enable row level security;

drop policy if exists "Administradores podem gerenciar composicoes de kits" on public.product_kit_items;
create policy "Administradores podem gerenciar composicoes de kits"
  on public.product_kit_items
  for all
  to authenticated
  using ((select public.is_admin()))
  with check ((select public.is_admin()));

grant select, insert, update, delete on public.product_kit_items to authenticated;
grant usage, select on sequence public.product_kit_items_id_seq to authenticated;
revoke all on public.product_kit_items from anon;

-- Mantem o campo updated_at consistente quando a composicao é alterada.
create or replace function public.update_product_kit_items_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists update_product_kit_items_updated_at on public.product_kit_items;
create trigger update_product_kit_items_updated_at
before update on public.product_kit_items
for each row execute function public.update_product_kit_items_updated_at();

revoke all on function public.update_product_kit_items_updated_at() from public;
grant execute on function public.update_product_kit_items_updated_at() to authenticated;
